### PR TITLE
Add more SPTPersistentCache tests

### PR DESCRIPTION
**Pull request by 8W9aG**
- Test the header expiries
- Test the garbage collection scheduler

### CODE REVIEW

**Comment by 8W9aG** [comment]
@spotify/objc-dev

**Comment by rastersize** [comment]
:+1:

**Comment by rastersize** [comment]
There are a few corner cases left here that could be tested if you want. See https://codecov.io/github/spotify/SPTPersistentCache/compare/c04480c...84153ba

:point_up: That link can always be found by clicking on the details for the codecov/patch status check.

**Comment by 8W9aG** [comment]
@rastersize soon ;), I will get them

**Pull request merged**
