### PR TITLE
Remove cache types

### PR DESCRIPTION
**Pull request by 8W9aG**
- Also cleanup documentation

### CODE REVIEW

**Comment by 8W9aG** [comment]
@spotify/objc-dev

**Comment by rastersize** [comment]
:+1:

**Comment by dflems** [comment]
Why remove the types header? When the types are used by more than one class (as they are in this case), I feel like it makes more sense to keep them in a separate header.

**Comment by 8W9aG** [comment]
In the API they are used in one header at a time

**Pull request merged**
