### PR TITLE
Update to use a NSOperationQueue instead of GCD

### PR DESCRIPTION
**Pull request by chrisbtreats**
Reopening version of https://github.com/spotify/SPTPersistentCache/pull/78

After analyzing some performance numbers, it seemed that a large number of interactions on the persistent cache where causing long read times. It turns out that you can flood the execution queue with things like unlocking or deleting and they would block operations like reads until the queue finished all of the operations that were enqueued before the read. The idea with this PR is to use a priority queue in the form of NSOperationQueue to allow reads to have a higher priority for reads than for unlocks or deletes.

I added some timing and a performance test in `SPTPersistentCachePerformance` that creates 200 locked items in the cache and then enqueues 200 unlocks followed immediately by 200 reads. I ran the test 3 times, first on the current GCD version and then on 2 versions using the NSOperationQueue, first with normal priority for all operation types and then with a high priority for reads and a low priority for unlocks.

Here are the times of the read sitting in the queue before execution begins. The test was run on an iPhone 6 running iOS 9.3.5. All times are in milliseconds.

| Type | Queue Average | Queue Min | Queue Max |
| --- | --- | --- | --- |
| Current GCD | 372.1658762 | 51.09783 | 968.4579 |
| NSOperationQueue Normal | 348.2155414 | 33.32054 | 963.0783 |
| NSOperationQueue Priority | 328.9230705 | 12.22912 | 909.4095 |

This shows close to a 12% increase in the average queue time and a 6% improvement over the max wait time.

There are some backwards compatibility breaking changes in this that modify a few methods (such as `removeDataForKeys`, `prune`,  `wipeLockedFiles`, and `wipeNonLockedFiles`) to be asynchronous instead of synchronous.

### CODE REVIEW

**Comment by 8W9aG** [comment]
👍

**Comment by chrisbtreats** [comment]
@rastersize and @spotify/objc-dev so what's your final opinion on the api breaking changes. Copying my comments from the other PR:

> I slightly misunderstood what dispatch_barrier_async was doing and it wasn't actually synchronous before. It is asynchronous but ensures exclusive execution of the task while no other tasks are executing. NSOperationQueue doesn't have an equivalent to dispatch_barrier_async. I can add those existing methods back but it worries me to have the same method having different semantics of not guaranteeing one operation at a time. My thought was it was better to have a breaking change than to have different semantics. One option is to leave the old methods with different semantics and mark them as deprecated.

**Comment by 8W9aG** [comment]
@chrisbtreats I think it's fine, something we should consider is that synchronous methods have been requested (see in the issues), i might work on doing these before the 1.1.0 release

**Comment by chrisbtreats** [comment]
Sounds good. I will merge later today. 

Adding synchronous methods should be pretty easy now. `NSOperationQueue` provides a method `- (void)addOperations:(NSArray<NSOperation *> *)ops 
    waitUntilFinished:(BOOL)wait;`

**Pull request merged**
