### PR TITLE
Fix style in NSError+SPTPersistentCacheDomainErrors

### PR DESCRIPTION
**Pull request by 8W9aG**
- Some minor style changes to the doc comments

### CODE REVIEW

**Comment by 8W9aG** [comment]
@spotify/objc-dev

**Comment by ChocoChipset** [comment]
:ear_of_rice:

**Comment by ChocoChipset** [comment]
Perhaps something to add to our style guide, @8W9aG ?

**Comment by 8W9aG** [comment]
I do think it would be good to settle on a style for our documentation (rather than just using what seems prevalent in the project)

**Comment by rastersize** [comment]
@8W9aG I’m working on such a thing. However tiiime. I need more of it :smile:

**Pull request merged**
