### PR TITLE
Add more SPTPersistentCache tests

### PR DESCRIPTION
**Pull request by 8W9aG**
- Test more failures within POSIX functions
- Test excessive TTL values

### CODE REVIEW

**Comment by 8W9aG** [comment]
@spotify/objc-dev

**Comment by ChocoChipset** [comment]
More tests! :yellow_heart:

**Comment by rastersize** [comment]
This looks fine from a code level, so :+1: on that.

However why aren’t we using the built-in wrapper instead? That is `NSFileHandle`.

> The NSFileHandle class is an object-oriented wrapper for a file descriptor. You use file handle objects to access data associated with files, sockets, pipes, and devices. **For files, you can read, write, and seek within the file.** For sockets, pipes, and devices, you can use a file handle object to monitor the device and process data asynchronously.

Emphasis mine on the part that’s relevant to us.

**Comment by 8W9aG** [comment]
@rastersize This is a good point, I will make do that in a follow up PR

**Comment by rastersize** [comment]
@8W9aG :+1:

**Pull request merged**
